dist: bionic
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest tests
  - pycodestyle --ignore=E402 pl_curve.py
  - python -m pytest --cov --cov-report tests
  
after_success:
  - codecov
