language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install pandas pytest matplotlib numpy pep8
# command to run tests
script:
  - pytest tests
  - pep8 pl_curve.py
